title = "Mini Lab Gitleaks Config"
[allowlist]
description = "Allowlisted patterns"
regexes = ["(example|dummy)"]

[[rules]]
id = "Generic Credential"
description = "Generic credentials"
regex = '''(?i)(password|secret|api[-_]?key)\s*[:=]\s*['"][A-Za-z0-9\-_]+['"]'''
