name: CI Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true

      - name: Build Docker Image
        run: docker build -t secure-mini-lab:local .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-mini-lab:local
          format: "table"
          exit-code: "1"
          severity: "HIGH,CRITICAL"

      - name: Install OPA
        run: |
          sudo wget -O /usr/local/bin/opa https://github.com/open-policy-agent/conftest/releases/download/v0.63.0/conftest_0.63.0_Linux_x86_64.tar.gz
          sudo chmod +x /usr/local/bin/opa

      - name: Run OPA Policy Checks
        run: conftest test k8s/*.yaml -p policy/k8s.rego
